/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testing.ci;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    public String getName() { return "testing-ci"; }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getName());
    }
}
